//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicadoDentalWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public short CitaId { get; set; }
        public short ClienteId { get; set; }
        public short DoctorId { get; set; }
        public System.DateTime? FechaHora { get; set; }
        public string Descripcion { get; set; }
        public string Comentarios { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
