//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicadoDentalWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public short CitaID { get; set; }
        public short ClienteID { get; set; }
        public short AdminID { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Hora { get; set; }
        public string Descripcion { get; set; }
        public string Comentarios { get; set; }
        public virtual Admin Admin { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
